#ifndef TOKENIZER_H_INCLUDED
#define TOKENIZER_H_INCLUDED

#include <stdio.h>

#include "common.h"
#include "array_list.h"

typedef enum {
    TOKEN_KW_BREAK = 0x0100,
    TOKEN_KW_CASE,
    TOKEN_KW_CONST,
    TOKEN_KW_CONTINUE,
    TOKEN_KW_DEFAULT,
    TOKEN_KW_DO,
    TOKEN_KW_ELSE,
    TOKEN_KW_FOR,
    TOKEN_KW_GOTO,
    TOKEN_KW_IF,
    TOKEN_KW_INLINE,
    TOKEN_KW_INT8_T,
    TOKEN_KW_UINT8_T,
    TOKEN_KW_LIKELY,
    TOKEN_KW_UNLIKELY,
    TOKEN_KW_RETURN,
    TOKEN_KW_SIZEOF,
    TOKEN_KW_SWITCH,
    TOKEN_KW_VOID,
    TOKEN_KW_WHILE,
    TOKEN_IDENTIFIER = 0x0200,
    TOKEN_CONST_DEC = 0x0400,
    TOKEN_CONST_BIN,
    TOKEN_CONST_HEX,
    TOKEN_CONST_CHAR,
    TOKEN_PUNCT_L_SP = 0x0800,
    TOKEN_PUNCT_R_SP,
    TOKEN_PUNCT_L_P,
    TOKEN_PUNCT_R_P,
    TOKEN_PUNCT_L_CP,
    TOKEN_PUNCT_R_CP,
    TOKEN_PUNCT_INC,
    TOKEN_PUNCT_DEC,
    TOKEN_PUNCT_AND,
    TOKEN_PUNCT_STAR,
    TOKEN_PUNCT_PLUS,
    TOKEN_PUNCT_MINUS,
    TOKEN_PUNCT_NEG,
    TOKEN_PUNCT_NOT,
    TOKEN_PUNCT_SLASH,
    TOKEN_PUNCT_PERCENT,
    TOKEN_PUNCT_SHL,
    TOKEN_PUNCT_SHR,
    TOKEN_PUNCT_LT,
    TOKEN_PUNCT_GT,
    TOKEN_PUNCT_LE,
    TOKEN_PUNCT_GE,
    TOKEN_PUNCT_EQ,
    TOKEN_PUNCT_NE,
    TOKEN_PUNCT_XOR,
    TOKEN_PUNCT_OR,
    TOKEN_PUNCT_LAND,
    TOKEN_PUNCT_LOR,
    TOKEN_PUNCT_QUESTION,
    TOKEN_PUNCT_COLON,
    TOKEN_PUNCT_SEMICOLON,
    TOKEN_PUNCT_ASSIGN,
    TOKEN_PUNCT_MULEQ,
    TOKEN_PUNCT_DIVEQ,
    TOKEN_PUNCT_MODEQ,
    TOKEN_PUNCT_PLUSEQ,
    TOKEN_PUNCT_MINUSEQ,
    TOKEN_PUNCT_SHLEQ,
    TOKEN_PUNCT_SHREQ,
    TOKEN_PUNCT_ANDEQ,
    TOKEN_PUNCT_OREQ,
    TOKEN_PUNCT_XOREQ,
    TOKEN_PUNCT_SET,
    TOKEN_PUNCT_CLR,
    TOKEN_PUNCT_COMMA,
    TOKEN_PUNCT_COMMENT,
    TOKEN_EOF = 0x1000,
    TOKEN_ERROR = 0x0000
} token_type_t;

typedef struct {
    str token;
    token_type_t type;
    uint_t line_num;
    uint_t column_pos;
} token_t;

typedef ARRAY_LIST_TYPE(const token_t *) token_lst_t;

void tokenize(FILE *fp, token_lst_t *token_lst);

#endif // TOKENIZER_H_INCLUDED
